# Generated by Django 4.0.1 on 2022-01-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_incomeexpense_remove_expense_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IncomeExpense',
            new_name='IncomeExpense_Info',
        ),
    ]
