# Generated by Django 4.0.1 on 2022-01-15 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_stats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
